:toc:
:toclevels: 3

== Curl commands for kickstarting
While working with eLabFTW's API, before implementing a new feature it's wise to test if something is even possible through *curl* commands. We'll be referring to this action as _kickstarting_ a feature.

=== On eLabFTW v5.0.4
==== Creating an empty sample
After exporting the API key for your account as a Bash variable (`export ELAB_KEY=8-8bd3f...`), run the following command:

```bash
curl -H "Content-Type: application/json" -H "Authorization: $ELAB_KEY" \ 
    -d '{ "category_id": 10, "tags": ["primo campione", "altro tag"] }' \
    -k -X POST https://old.elabftw.net/api/v2/items/
```

* The header (`-H or --header`) section tells eLab that the content is in json format and that the authentication must occur via API key.
* The data (`-d` or `--data`) section contains the payload, which unfortunately for eLabFTW 5.0.4 is limited to category ID (10 for "Sample" in OUR VERY OWN instance of eLab) and tags.
* `-k` or  `--insecure` makes curl skip the verification step and proceed without checking; necessary if your instance of eLab has a self-signed SSL certificate - or no certificate at all.
* The method (`-X` or `--request`) section decides the method to use when starting the transfer; link:https://en.wikipedia.org/wiki/POST_(HTTP)[HTTP POST^] is used to create new content on eLab.
* Replace `+https://old.elabftw.net/api/v2/items/+` with the url to the API of your instance of eLabFTW (e.g. "https://elabftw.selfhosted.it:8080/api/v2/items").

NOTE: In Bash single (`'`) and double (`"`) quotation marks are slightly different, as single quotes treat the content literally and do not expand variables (i.e. `'Authorization: $API_KEY'` will try to authenticate you to the server literally as `*$API_KEY*` instead of using your key - the content of the variable).

==== Opening an item by ID
If you know the ID of the item you wish to get data about, the curl command would be:

```bash
ITEM_ID=123
curl -H "Content-Type: application/json" -H "Authorization: $ELAB_KEY" \ 
    -k -X GET https://old.elabftw.net/api/v2/items/$ITEM_ID
```

The standard output is "minified", unless jq is added to the pipeline:

```bash
curl -H "Content-Type: application/json" -H "Authorization: $ELAB_KEY" \ 
    -k -X GET https://old.elabftw.net/api/v2/items/$ITEM_ID | jq | less
```

=== On eLabFTW v5.1.15
==== Creating an empty sample
v5.1.x has huge improvements for item creation and update. After exporting the API key for your account as a Bash variable (`export ELAB_KEY=8-8bd3f...`), run the following command:

```bash
curl -H "Content-Type: application/json" -H "Authorization: $ELAB_KEY" \ 
    -d '{ "template": 10, "title":"My new sample", "body":"<p>Brief description in raw HTML</p>", "tags": ["primo campione", "altro tag"] }' \
    -k -X POST https://demo.elabftw.net/api/v2/items/
```

* The header (`-H or --header`) section tells eLab that the content is in json format and that the authentication must occur via API key.
* The data (`-d` or `--data`) section contains the payload; in v5.1.15 "category_id" has been replaced by "template" and many more fields have been added, which means the user is now capable of populating an item with a single command much like how it's always been the case for the experiments. 
* `-k` or  `--insecure` makes curl skip the verification step and proceed without checking; necessary if your instance of eLab has a self-signed SSL certificate - or no certificate at all.
* The method (`-X` or `--request`) section decides the method to use when starting the transfer; link:https://en.wikipedia.org/wiki/POST_(HTTP)[HTTP POST^] is used to create new content on eLab.
* Replace `+https://demo.elabftw.net/api/v2/items/+` with the url to the API of your instance of eLabFTW (e.g. "https://elabftw.selfhosted.it:8080/api/v2/items").

==== Creating a sample from JSON file
Assuming you have a JSON file compliant to your eLabFTW instance, you can run the previous command in a "quieter" way:

```bash
curl -H "Content-Type: application/json" -H "Authorization: $ELAB_KEY" \ 
    -d '@/path/to/sample.json' \
    -k -X POST https://demo.elabftw.net/api/v2/items/
```

NOTE: The path to the JSON file can be relative (e.g. `@tests/example.json`). +
The `@` symbol is required.

==== Opening an item by ID
Item visualization works the same as in v5.0.4.

```bash
ITEM_ID=123
curl -H "Content-Type: application/json" -H "Authorization: $ELAB_KEY" \ 
    -k -X GET https://old.elabftw.net/api/v2/items/$ITEM_ID
```

The standard output is "minified", unless jq is added to the pipeline:

```bash
curl -H "Content-Type: application/json" -H "Authorization: $ELAB_KEY" \ 
    -k -X GET https://old.elabftw.net/api/v2/items/$ITEM_ID | jq | less
```

== Debugging with curl
Oftentimes executing a certain command returns a different result from what's expected. What follows is a "journal" of curl prompts I've tried to achieve a certain result which instead returned something wrong or unexpected.

=== On eLabFTW v5.1.15
==== Posting metadata in "extra fields" +[Items]+
Link to GitHub Issue: link:https://github.com/elabftw/elabftw/issues/5480[elabftw / issues / 5480].

WARNING: The issue has been closed as the problem is solved in v5.2.0-alpha.

I want to create a new item on the demo instance (demo.elabftw.net) via API using curl; I copy the item model directly from the link:https://doc.elabftw.net/api/v2/#/Items/post-item[official API documentation^] with no editing and paste it in a variable `$MYJSON`:

```bash
export MYJSON='{
  "body": "<h1>Section title</h1><p>Main text of resource</p>",
  "canread": "{\"base\": 30, \"teams\": [], \"users\": [], \"teamgroups\": []}",
  "canwrite": "{\"base\": 20, \"teams\": [], \"users\": [], \"teamgroups\": []}",
  "content_type": 1,
  "metadata": "{ \"extra_fields\": { \"For example\": { \"type\": \"text\", \"value\": \"With a value\", \"required\": true, \"description\": \"An extra field of type text\" } } }",
  "rating": 0,
  "status": 1,
  "template": 1,
  "tags": [
    "TIRF",
    "Nikon",
    "mandatory booking"
  ],
  "title": "TIRF microscope"
}'
```

After that I launch curl with the following options - where $ELAB_KEY is my personal API key:

```bash
curl -H "Content-Type: application/json" -H "Authorization: $ELAB_KEY" \
    -k -X POST https://demo.elabftw.net/api/v2/items/ \
    -d "$MYJSON"

```

All is good, I don't get any error and the new item is created on the demo. Title, tags, template/category and status are exactly what I want; however:

* The body field is clear;
* The metadata/extra fields are clear - or set to the template's default.

I've also tried many small changes, like:

* Storing my JSON in a file instead of a Bash variable;
* Pasting the contents of the JSON directly into my terminal while running curl;
* Editing the model to fit a different template's default extra fields:

```json
{
  "body": "<h1>Section title</h1><p>Main text of resource</p>",
  "canread": "{\"base\": 30, \"teams\": [], \"users\": [], \"teamgroups\": []}",
  "canwrite": "{\"base\": 20, \"teams\": [], \"users\": [], \"teamgroups\": []}",
  "content_type": 1,
  "metadata": "{\"extra_fields\": {\"Concentration\": {\"type\": \"number\", \"value\": \"20\", \"description\": \"in μg/μL\"}, \"Growth temperature\": {\"type\": \"text\", \"value\": \"50\", \"description\": \"in °C\"}}}",
  "rating": 3,
  "status": 1,
  "template": 5,
  "tags": [
    "TIRF",
    "Nikon",
    "mandatory booking"
  ],
  "title": "TIRF microscope"
}
```

While the original example contains a single extra field called "For example", my edited file contains two extra fields supported officially on the eLabFTW's demo instance (*Concentration* and *Growth temperature*) for the _Plasmid_ template. I've also changed the template value from 1 to 5 (Plasmid) and the rating from 0 (no rating) to 3, discovering that not even the rating field is set to the value I provide.
